### PR TITLE
Updating value by prop change

### PR DESCRIPTION
**Pull request by andylacko**
Hello I quickly created principe, how the component can update value of switch after changing the prop, it **need to be tested** , but it should work, please integrate

### CODE REVIEW

**Comment by mohithg** [comment]
Hi, @andylaci Thanks for your Pull Request though, but I have made necessary changes after testing in 1.2.1.

Kindly check version 1.2.1 and let me know if you still face any issue.

**Comment by andylacko** [comment]
ok, not a problem, but the version 1.2.1 throws a lot of `Cannot find module` errors, eg. ftlabs~fastclick@v0.6.11 . Am I doing something wrong? In previous version there was no problem

**Comment by mohithg** [comment]
Can you clear your npm cache and try?

**Comment by andylacko** [comment]
cleared cache, still this error `Browserify Error { Error: Cannot find module 'component~delegate@0.2.3' from '/.../node_modules/mohithg-switchery/dist'
    at /.../node_modules/browser-resolve/node_modules/resolve/lib/async.js`

**Comment by mohithg** [comment]
Hmm, can you try in a clean project, or may be removing all node_modules? or give me steps to reproduce.

**Comment by andylacko** [comment]
I removed node modules with `rm -Rf node_modules/` , then run `yarn install` and everything works fine just `react-switchery` library is reporting errors, don't know, how to reproduce more. It seems, like the library can't find any of it's dependencies

**Comment by mohithg** [comment]
May be yarn is taking the old version because of its yarn.lock file. Could you please check `1.2.2`
I just tried in a clean react-create-app and it works fine!
Can you please confirm?

**Comment by andylacko** [comment]
same problem, maybe browserify is generating errors, it is little bit old devstack. But don't know what could be wrong, because every other library is working fine

**Comment by mohithg** [comment]
I actually updated Switchery to latest version so that `size` option is supported. May be that is causing the issues.

**Pull request closed without merging**
